# -*- coding: utf-8 -*-
##
## This file is part of Invenio.
## Copyright (C) 2013 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

notifications:
  email: false

services:
  - mysql # will start mysqld
  - rabbitmq # will start rabbitmq-server
  - redis # will start memcached

python:
  - "2.7"
  - "2.6"

install:
  - "sudo apt-get update"
  - "sudo apt-get install apache2 libapache2-mod-wsgi ssl-cert poppler-utils --fix-missing"
  - "sudo a2enmod actions"
  - "sudo a2enmod rewrite"
  - "sudo mkdir /etc/apache2/ssl"
  - "mkdir -p /home/travis/.virtualenvs/invenio/var/tmp/"
  - "sudo /usr/sbin/make-ssl-cert /usr/share/ssl-cert/ssleay.cnf /etc/apache2/ssl/apache.pem"
  - "travis_retry sudo pip install --upgrade virtualenvwrapper"
  - ". `which virtualenvwrapper.sh`"
  - "mkvirtualenv invenio"
  - "workon invenio"
  - "travis_retry pip install nose"
  - "travis_retry pip install . --process-dependency-links --allow-all-external"
  - "inveniomanage config create secret-key"
  - "inveniomanage config set CFG_EMAIL_BACKEND flask.ext.email.backends.console.Mail"
  - "inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami`"

before_script:
  - "inveniomanage apache create-config"
#  - "sudo ln -s $WORKON_HOME/invenio/etc/apache/invenio-apache-vhost.conf /etc/apache2/sites-available/invenio"
#  - "sudo ln -s $WORKON_HOME/invenio/etc/apache/invenio-apache-vhost-ssl.conf /etc/apache2/sites-available/invenio-ssl"
#  - "sudo /usr/sbin/a2dissite default || echo ':('"
#  - "sudo /usr/sbin/a2ensite invenio" # enable Invenio web site
#  - "sudo /usr/sbin/a2ensite invenio-ssl" # enable Invenio secure web site
#  - "sudo /usr/sbin/a2enmod ssl" # enable SSL module
#  - "sudo /usr/sbin/a2enmod xsendfile || echo ':('"
#  - "sudo apachectl configtest && sudo service apache2 restart || echo 'Apache failed ...'"
  - "inveniomanage database init --yes-i-know"
  - "inveniomanage database create"
  - "inveniomanage demosite create"
  - "inveniomanage demosite populate --file=invenio_demosite/data/labs_record_marc_data.xml"

script:
  - "nosetests invenio_demosite/testsuite/regression"
#  - "python setup.py test"
